Repository clxering/Effective-Java-3rd-edition-Chinese-English-bilingual, pull requests merged in 2019-02, with the labels that each got.

#57 修正模版问题并批量修改了格式
  .github/CONTRIBUTING.md
  .github/CONTRIBUTING_zh.md
  Chapter-2/Chapter-2-Item-8-Avoid-finalizers-and-cleaners.md
  Chapter-3/Chapter-3-Item-11-Always-override-hashCode-when-you-override-equals.md
  Chapter-3/Chapter-3-Item-12-Always-override-toString.md
  Chapter-3/Chapter-3-Item-13-Override-clone-judiciously.md
  Chapter-4/Chapter-4-Item-15-Minimize-the-accessibility-of-classes-and-members.md
  Chapter-4/Chapter-4-Item-16-In-public-classes-use-accessor-methods-not-public-fields.md
  Chapter-4/Chapter-4-Item-17-Minimize-mutability.md
  Chapter-4/Chapter-4-Item-18-Favor-composition-over-inheritance.md
  Chapter-4/Chapter-4-Item-19-Design-and-document-for-inheritance-or-else-prohibit-it.md
  Chapter-4/Chapter-4-Item-20-Prefer-interfaces-to-abstract-classes.md
  Chapter-4/Chapter-4-Item-21-Design-interfaces-for-posterity.md
  Chapter-4/Chapter-4-Item-22-Use-interfaces-only-to-define-types.md
  Chapter-4/Chapter-4-Item-23-Prefer-class-hierarchies-to-tagged-classes.md
  Chapter-4/Chapter-4-Item-24-Favor-static-member-classes-over-nonstatic.md
  Chapter-4/Chapter-4-Item-25-Limit-source-files-to-a-single-top-level-class.md
  Chapter-5/Chapter-5-Item-26-Do-not-use-raw-types.md
  Chapter-5/Chapter-5-Item-28-Prefer-lists-to-arrays.md
  Chapter-5/Chapter-5-Item-29-Favor-generic-types.md
  Chapter-5/Chapter-5-Item-31-Use-bounded-wildcards-to-increase-API-flexibility.md
  Chapter-6/Chapter-6-Item-34-Use-enums-instead-of-int-constants.md
  Chapter-6/Chapter-6-Item-35-Use-instance-fields-instead-of-ordinals.md
Labels: Bugfix, Improvement

#59 init Item 37
  Chapter-6/Chapter-6-Item-36-Use-EnumSet-instead-of-bit-fields.md
  Chapter-6/Chapter-6-Item-37-Use-EnumMap-instead-of-ordinal-indexing.md
  README.md
Labels: Initialization

#62 init Item 38
  Chapter-6/Chapter-6-Item-38-Emulate-extensible-enums-with-interfaces.md
  README.md
Labels: Initialization

#63 初始化 Item 39 ，修改部分格式并添加遗漏的 Item 40-41
  Chapter-6/Chapter-6-Item-39-Prefer-annotations-to-naming-patterns.md
  Chapter-6/Chapter-6-Item-40-Consistently-use-the-Override-annotation.md
  Chapter-6/Chapter-6-Item-41-Use-marker-interfaces-to-define-types.md
  Chapter-7/Chapter-7-Introduction.md
  Chapter-7/Chapter-7-Item-42-Prefer-lambdas-to-anonymous-classes.md
  Chapter-7/Chapter-7-Item-43-Prefer-method-references-to-lambdas.md
  Chapter-7/Chapter-7-Item-44-Favor-the-use-of-standard-functional-interfaces.md
  Chapter-7/Chapter-7-Item-45-Use-streams-judiciously.md
  Chapter-7/Chapter-7-Item-46-Prefer-side-effect-free-functions-in-streams.md
  Chapter-7/Chapter-7-Item-47-Prefer-Collection-to-Stream-as-a-return-type.md
  Chapter-7/Chapter-7-Item-48-Use-caution-when-making-streams-parallel.md
  Chapter-9/Chapter-9-Introduction.md
  Chapter-9/Chapter-9-Item-57-Minimize-the-scope-of-local-variables.md
  Chapter-9/Chapter-9-Item-58-Prefer-for-each-loops-to-traditional-for-loops.md
  Chapter-9/Chapter-9-Item-59-Know-and-use-the-libraries.md
  Chapter-9/Chapter-9-Item-60-Avoid-float-and-double-if-exact-answers-are-required.md
  Chapter-9/Chapter-9-Item-61-Prefer-primitive-types-to-boxed-primitives.md
  Chapter-9/Chapter-9-Item-62-Avoid-strings-where-other-types-are-more-appropriate.md
  Chapter-9/Chapter-9-Item-63-Beware-the-performance-of-string-concatenation.md
  Chapter-9/Chapter-9-Item-64-Refer-to-objects-by-their-interfaces.md
  Chapter-9/Chapter-9-Item-65-Prefer-interfaces-to-reflection.md
  Chapter-9/Chapter-9-Item-66-Use-native-methods-judiciously.md
  Chapter-9/Chapter-9-Item-67-Optimize-judiciously.md
  Chapter-9/Chapter-9-Item-68-Adhere-to-generally-accepted-naming-conventions.md
  README.md
Labels: Initialization

#65 init Item 40
  Chapter-6/Chapter-6-Item-40-Consistently-use-the-Override-annotation.md
  README.md
Labels: Initialization

#67 init Item 41
  Chapter-6/Chapter-6-Item-41-Use-marker-interfaces-to-define-types.md
  README.md
Labels: Initialization

#70 增加翻页特性并修正部分格式
  Chapter-2/Chapter-2-Introduction.md
  Chapter-2/Chapter-2-Item-1-Consider-static-factory-methods-instead-of-constructors.md
  Chapter-2/Chapter-2-Item-2-Consider-a-builder-when-faced-with-many-constructor-parameters.md
  Chapter-2/Chapter-2-Item-3-Enforce-the-singleton-property-with-a-private-constructor-or-an-enum-type.md
  Chapter-2/Chapter-2-Item-4-Enforce-noninstantiability-with-a-private-constructor.md
  Chapter-2/Chapter-2-Item-5-Prefer-dependency-injection-to-hardwiring-resources.md
  Chapter-2/Chapter-2-Item-6-Avoid-creating-unnecessary-objects.md
  Chapter-2/Chapter-2-Item-7-Eliminate-obsolete-object-references.md
  Chapter-2/Chapter-2-Item-8-Avoid-finalizers-and-cleaners.md
  Chapter-2/Chapter-2-Item-9-Prefer-try-with-resources-to-try-finally.md
  Chapter-3/Chapter-3-Introduction.md
  Chapter-3/Chapter-3-Item-10-Obey-the-general-contract-when-overriding-equals.md
  Chapter-3/Chapter-3-Item-11-Always-override-hashCode-when-you-override-equals.md
  Chapter-3/Chapter-3-Item-12-Always-override-toString.md
  Chapter-3/Chapter-3-Item-13-Override-clone-judiciously.md
  Chapter-3/Chapter-3-Item-14-Consider-implementing-Comparable.md
  Chapter-4/Chapter-4-Introduction.md
  Chapter-4/Chapter-4-Item-15-Minimize-the-accessibility-of-classes-and-members.md
  Chapter-4/Chapter-4-Item-16-In-public-classes-use-accessor-methods-not-public-fields.md
  Chapter-4/Chapter-4-Item-17-Minimize-mutability.md
  Chapter-4/Chapter-4-Item-18-Favor-composition-over-inheritance.md
  Chapter-4/Chapter-4-Item-19-Design-and-document-for-inheritance-or-else-prohibit-it.md
  Chapter-4/Chapter-4-Item-20-Prefer-interfaces-to-abstract-classes.md
  Chapter-4/Chapter-4-Item-21-Design-interfaces-for-posterity.md
  Chapter-4/Chapter-4-Item-22-Use-interfaces-only-to-define-types.md
  Chapter-4/Chapter-4-Item-23-Prefer-class-hierarchies-to-tagged-classes.md
  Chapter-4/Chapter-4-Item-24-Favor-static-member-classes-over-nonstatic.md
  Chapter-4/Chapter-4-Item-25-Limit-source-files-to-a-single-top-level-class.md
  Chapter-5/Chapter-5-Introduction.md
  Chapter-5/Chapter-5-Item-26-Do-not-use-raw-types.md
  Chapter-5/Chapter-5-Item-27-Eliminate-unchecked-warnings.md
  Chapter-5/Chapter-5-Item-28-Prefer-lists-to-arrays.md
  Chapter-5/Chapter-5-Item-29-Favor-generic-types.md
  Chapter-5/Chapter-5-Item-30-Favor-generic-methods.md
  Chapter-5/Chapter-5-Item-31-Use-bounded-wildcards-to-increase-API-flexibility.md
  Chapter-5/Chapter-5-Item-32-Combine-generics-and-varargs-judiciously.md
  Chapter-5/Chapter-5-Item-33-Consider-typesafe-heterogeneous-containers.md
  Chapter-6/Chapter-6-Introduction.md
  Chapter-6/Chapter-6-Item-34-Use-enums-instead-of-int-constants.md
  Chapter-6/Chapter-6-Item-35-Use-instance-fields-instead-of-ordinals.md
  Chapter-6/Chapter-6-Item-36-Use-EnumSet-instead-of-bit-fields.md
  Chapter-6/Chapter-6-Item-37-Use-EnumMap-instead-of-ordinal-indexing.md
  Chapter-6/Chapter-6-Item-38-Emulate-extensible-enums-with-interfaces.md
  Chapter-6/Chapter-6-Item-39-Prefer-annotations-to-naming-patterns.md
  Chapter-6/Chapter-6-Item-40-Consistently-use-the-Override-annotation.md
  Chapter-6/Chapter-6-Item-41-Use-marker-interfaces-to-define-types.md
Labels: Other

#68 完成第九章简介翻译
  Chapter-9/Chapter-9-Introduction.md
Labels: Initialization
