Repository clxering/Effective-Java-3rd-edition-Chinese-English-bilingual, pull requests merged in 2019-01, with the labels that each got.

#30 Add Item 31 init
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Bugfix_or_Improvement.md
  .github/ISSUE_TEMPLATE/Discussion_or_Suggestion.md
  .github/PULL_REQUEST_TEMPLATE.md
  Chapter-5-Item-31-Use-bounded-wildcards-to-increase-API-flexibility.md
  README.md
Labels: Initialization

#33 修改 Item 1 格式和部分翻译
  Chapter-2-Item-1-Consider-static-factory-methods-instead-of-constructors.md
Labels: Bugfix, Improvement

#35 修改 Item 2 中格式、语义语序、用词欠准确的问题
  Chapter-2-Item-2-Consider-a-builder-when-faced-with-many-constructor-parameters.md
Labels: Bugfix, Improvement

#39 Chapter2 item-8,item-9 Improvement
  Chapter-2-Item-8-Avoid-finalizers-and-cleaners.md
  Chapter-2-Item-9-Prefer-try-with-resources-to-try-finally.md
Labels: Bugfix, Improvement

#41 修复 Chapter 5 格式和翻译问题
  Chapter-5-Introduction.md
  Chapter-5-Item-26-Do-not-use-raw-types.md
  Chapter-5-Item-27-Eliminate-unchecked-warnings.md
  Chapter-5-Item-28-Prefer-lists-to-arrays.md
  Chapter-5-Item-29-Favor-generic-types.md
  Chapter-5-Item-31-Use-bounded-wildcards-to-increase-API-flexibility.md
  README.md
Labels: Improvement

#45 update contents, init Item 36
  Chapter-6-Item-36-Use-EnumSet-instead-of-bit-fields.md
  README.md
  image/alipay.png
  image/wechatpay.png
Labels: Initialization

#47 修复 Item 3 的部分问题
  Chapter-2-Item-3-Enforce-the-singleton-property-with-a-private-constructor-or-an-enum-type.md
Labels: Bugfix, Improvement

#49 修复 Chapter 2 格式和翻译问题
  Chapter-2-Item-1-Consider-static-factory-methods-instead-of-constructors.md
  Chapter-2-Item-2-Consider-a-builder-when-faced-with-many-constructor-parameters.md
  Chapter-2-Item-4-Enforce-noninstantiability-with-a-private-constructor.md
  Chapter-2-Item-5-Prefer-dependency-injection-to-hardwiring-resources.md
  Chapter-2-Item-6-Avoid-creating-unnecessary-objects.md
  Chapter-2-Item-7-Eliminate-obsolete-object-references.md
  Chapter-2-Item-8-Avoid-finalizers-and-cleaners.md
  Chapter-2-Item-9-Prefer-try-with-resources-to-try-finally.md
  README.md
Labels: Bugfix, Improvement
