Repository clxering/Effective-Java-3rd-edition-Chinese-English-bilingual, pull requests merged in 2019-03, with the labels that each got.

#76 Chapter 7 init
  Chapter-7/Chapter-7-Introduction.md
  Chapter-7/Chapter-7-Item-42-Prefer-lambdas-to-anonymous-classes.md
  Chapter-7/Chapter-7-Item-43-Prefer-method-references-to-lambdas.md
  Chapter-7/Chapter-7-Item-44-Favor-the-use-of-standard-functional-interfaces.md
  Chapter-7/Chapter-7-Item-45-Use-streams-judiciously.md
  Chapter-7/Chapter-7-Item-46-Prefer-side-effect-free-functions-in-streams.md
  Chapter-7/Chapter-7-Item-47-Prefer-Collection-to-Stream-as-a-return-type.md
  Chapter-7/Chapter-7-Item-48-Use-caution-when-making-streams-parallel.md
  README.md
Labels: Initialization

#78 Chapter 8 init
  Chapter-8/Chapter-8-Introduction.md
  Chapter-8/Chapter-8-Item-49-Check-parameters-for-validity.md
  Chapter-8/Chapter-8-Item-50-Make-defensive-copies-when-needed.md
  Chapter-8/Chapter-8-Item-51-Design-method-signatures-carefully.md
  Chapter-8/Chapter-8-Item-52-Use-overloading-judiciously.md
  Chapter-8/Chapter-8-Item-53-Use-varargs-judiciously.md
  Chapter-8/Chapter-8-Item-54-Return-empty-collections-or-arrays-not-nulls.md
  Chapter-8/Chapter-8-Item-55-Return-optionals-judiciously.md
  Chapter-8/Chapter-8-Item-56-Write-doc-comments-for-all-exposed-API-elements.md
  README.md
Labels: Initialization

#80 Chapter 9 init
  Chapter-9/Chapter-9-Introduction.md
  Chapter-9/Chapter-9-Item-57-Minimize-the-scope-of-local-variables.md
  Chapter-9/Chapter-9-Item-58-Prefer-for-each-loops-to-traditional-for-loops.md
  Chapter-9/Chapter-9-Item-59-Know-and-use-the-libraries.md
  Chapter-9/Chapter-9-Item-60-Avoid-float-and-double-if-exact-answers-are-required.md
  Chapter-9/Chapter-9-Item-61-Prefer-primitive-types-to-boxed-primitives.md
  Chapter-9/Chapter-9-Item-62-Avoid-strings-where-other-types-are-more-appropriate.md
  Chapter-9/Chapter-9-Item-63-Beware-the-performance-of-string-concatenation.md
  Chapter-9/Chapter-9-Item-64-Refer-to-objects-by-their-interfaces.md
  Chapter-9/Chapter-9-Item-65-Prefer-interfaces-to-reflection.md
  Chapter-9/Chapter-9-Item-66-Use-native-methods-judiciously.md
  Chapter-9/Chapter-9-Item-67-Optimize-judiciously.md
  Chapter-9/Chapter-9-Item-68-Adhere-to-generally-accepted-naming-conventions.md
  README.md
Labels: Initialization

#81 发布 Chapter 9
  Chapter-9/Chapter-9-Introduction.md
  Chapter-9/Chapter-9-Item-57-Minimize-the-scope-of-local-variables.md
  Chapter-9/Chapter-9-Item-58-Prefer-for-each-loops-to-traditional-for-loops.md
  Chapter-9/Chapter-9-Item-59-Know-and-use-the-libraries.md
  Chapter-9/Chapter-9-Item-60-Avoid-float-and-double-if-exact-answers-are-required.md
  Chapter-9/Chapter-9-Item-61-Prefer-primitive-types-to-boxed-primitives.md
  Chapter-9/Chapter-9-Item-62-Avoid-strings-where-other-types-are-more-appropriate.md
  Chapter-9/Chapter-9-Item-63-Beware-the-performance-of-string-concatenation.md
  Chapter-9/Chapter-9-Item-64-Refer-to-objects-by-their-interfaces.md
  Chapter-9/Chapter-9-Item-65-Prefer-interfaces-to-reflection.md
  Chapter-9/Chapter-9-Item-66-Use-native-methods-judiciously.md
  Chapter-9/Chapter-9-Item-67-Optimize-judiciously.md
  Chapter-9/Chapter-9-Item-68-Adhere-to-generally-accepted-naming-conventions.md
  README.md
Labels: Published

#84 Chapter 10 init
  Chapter-10/Chapter-10-Introduction.md
  Chapter-10/Chapter-10-Item-69-Use-exceptions-only-for-exceptional-conditions.md
  Chapter-10/Chapter-10-Item-70-Use-checked-exceptions-for-recoverable-conditions-and-runtime-exceptions-for-programming-errors.md
  Chapter-10/Chapter-10-Item-71-Avoid-unnecessary-use-of-checked-exceptions.md
  Chapter-10/Chapter-10-Item-72-Favor-the-use-of-standard-exceptions.md
  Chapter-10/Chapter-10-Item-73-Throw-exceptions-appropriate-to-the-abstraction.md
  Chapter-10/Chapter-10-Item-74-Document-all-exceptions-thrown-by-each-method.md
  Chapter-10/Chapter-10-Item-75-Include-failure-capture-information-in-detail-messages.md
  Chapter-10/Chapter-10-Item-76-Strive-for-failure-atomicity.md
  Chapter-10/Chapter-10-Item-77-Don’t-ignore-exceptions.md
  README.md
Labels: Initialization

#86 Chapter 11 init
  Chapter-11/Chapter-11-Introduction.md
  Chapter-11/Chapter-11-Item-78-Synchronize-access-to-shared-mutable-data.md
  Chapter-11/Chapter-11-Item-79-Avoid-excessive-synchronization.md
  Chapter-11/Chapter-11-Item-80-Prefer-executors,-tasks,-and-streams-to-threads.md
  Chapter-11/Chapter-11-Item-81-Prefer-concurrency-utilities-to-wait-and-notify.md
  Chapter-11/Chapter-11-Item-82-Document-thread-safety.md
  Chapter-11/Chapter-11-Item-83-Use-lazy-initialization-judiciously.md
  Chapter-11/Chapter-11-Item-84-Don’t-depend-on-the-thread-scheduler.md
  README.md
Labels: Initialization

#88 Chapter 12 init
  Chapter-12/Chapter-12-Introduction.md
  Chapter-12/Chapter-12-Item-85-Prefer-alternatives-to-Java-serialization.md
  Chapter-12/Chapter-12-Item-86-Implement-Serializable-with-great-caution.md
  Chapter-12/Chapter-12-Item-87-Consider-using-a-custom-serialized-form.md
  Chapter-12/Chapter-12-Item-88-Write-readObject-methods-defensively.md
  Chapter-12/Chapter-12-Item-89-For-instance-control-prefer-enum-types-to-readResolve.md
  Chapter-12/Chapter-12-Item-90-Consider-serialization-proxies-instead-of-serialized-instances.md
  README.md
Labels: Initialization

#89 发布 Chapter 12
  Chapter-12/Chapter-12-Introduction.md
  Chapter-12/Chapter-12-Item-85-Prefer-alternatives-to-Java-serialization.md
  Chapter-12/Chapter-12-Item-86-Implement-Serializable-with-great-caution.md
  Chapter-12/Chapter-12-Item-87-Consider-using-a-custom-serialized-form.md
  Chapter-12/Chapter-12-Item-88-Write-readObject-methods-defensively.md
  Chapter-12/Chapter-12-Item-89-For-instance-control-prefer-enum-types-to-readResolve.md
  Chapter-12/Chapter-12-Item-90-Consider-serialization-proxies-instead-of-serialized-instances.md
  README.md
Labels: Published

#90 resolve issue #73
  Chapter-2/Chapter-2-Item-1-Consider-static-factory-methods-instead-of-constructors.md
Labels: Improvement

#91 resolve issue #74
  Chapter-2/Chapter-2-Item-2-Consider-a-builder-when-faced-with-many-constructor-parameters.md
Labels: Improvement

#92 resolve issue #75
  Chapter-2/Chapter-2-Item-6-Avoid-creating-unnecessary-objects.md
Labels: Improvement
